---

- name: install packages
  yum:
    name: ganglia-gmond
    state: present
  tags:
    - ganglia_mond_install
    - ganglia_mond
    - install
    - ganglia


- name: configure
  template:
    src: gmond.conf.el7.j2
    dest: "{{ ganglia_gmon_conf_path }}"
  tags:
    - ganglia_mond_configure
    - ganglia_mond
    - configure
    - ganglia

- name: restart gmond
  service:
    name: gmond
    state: restarted
    enabled: yes
  tags:
    - ganglia_mond_service
    - ganglia_mond
    - ganglia_service
    - ganglia
    - service
